DROP DATABASE IF EXISTS ptpm_doiTac;
CREATE DATABASE ptpm_doiTac;
USE ptpm_doiTac;

DROP TABLE IF EXISTS khachHang;
CREATE TABLE khachHang
(
    maKhachHang  INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    tenKhachHang VARCHAR(255) NOT NULL,
    ngaySinh     DATE NOT NULL,
    diaChi       VARCHAR(255) NOT NULL,
    soDienThoai  VARCHAR(255) UNIQUE NOT NULL,
    mail         VARCHAR(255) UNIQUE NOT NULL,
    ngayThamGia  DATETIME            DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS nhaCungCap;
CREATE TABLE nhaCungCap
(
    maNhaCungCap  INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    tenNhaCungCap VARCHAR(255) NOT NULL,
    diaChi        VARCHAR(255) NOT NULL,
    mail          VARCHAR(255) UNIQUE NOT NULL,
    soDienThoai   VARCHAR(255) UNIQUE NOT NULL
);

SHOW DATABASES ;


SELECT COUNT(*) FROM khachhang;
SELECT COUNT(*) FROM nhaCungCap;



SELECT * FROM khachhang ORDER BY ngaySinh;

SELECT * FROM nhaCungCap;