DROP DATABASE IF EXISTS ptpm;
CREATE DATABASE ptpm;

USE ptpm;

DROP TABLE IF EXISTS ram;
CREATE TABLE ram (
	ma INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ten INT UNSIGNED
);

INSERT INTO ram (ma, ten) VALUES
(NULL, 4);

UPDATE ram 
SET ten = 8 
WHERE ma = 2;

SELECT * FROM ram;

DROP TABLE IF EXISTS rom;
CREATE TABLE rom (
	ma INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ten INT UNSIGNED
);

DROP TABLE IF EXISTS mauSac;
CREATE TABLE mauSac (
	ma INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(255)
);

DROP TABLE IF EXISTS xuatXu;
CREATE TABLE xuatXu (
	ma INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(255)
);

DROP TABLE IF EXISTS thuongHieu;
CREATE TABLE thuongHieu (
	ma INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(255)
);

DROP TABLE IF EXISTS heDieuHanh;
CREATE TABLE heDieuHanh (
	ma INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(255)
);